version: "3.7"

services:

  magento-web:
    build:
      context: ./mage/
    ports:
      - 2020:80
    expose:
      - 10000
    volumes:
      - ./mage/:/usr/share/nginx/html/
      - ./assets/mage.conf:/etc/nginx/conf.d/mage.conf
      - ./assets/nginx.conf:/etc/nginx/nginx.conf
      - ./assets/www.conf:/etc/php-fpm.d/www.conf
    tty: true
    command: >
      sh -c "nginx && mkdir -p /run/php-fpm/ && php-fpm && tail -f /dev/null"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.6.43
    ports:
      - 3310:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
      - MYSQL_DATABASE=magento
      - MYSQL_ROOT_PASSWORD=root_password
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root_password --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

